const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  navigationCategories: [
    { id: 'furniture', name: 'Furniture' },
    { id: 'chair', name: 'Chair' },
    { id: 'table', name: 'Table' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'bedroom', name: 'Bedroom' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      price: 30,
      stars: 3,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed1.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 4,
      discount: '-20%',
      featured: true,
      saleOff: true,
      topRated: true,
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed2.jpg',
      favourite: false,
      comparison: false,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed3.png',
      favourite: false,
      comparison: false,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed4.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      topSeller: true,
      saleOff: true,
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed5.jpg',
      favourite: true,
      comparison: false,
      userRating: 0,
      topSeller: true,
      saleOff: true,
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed6.jpg',
      favourite: true,
      comparison: false,
      userRating: 4,
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed7.jpg',
      favourite: true,
      comparison: false,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed8.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed9.jpg',
      favourite: false,
      comparison: false,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed10.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 1,
      hotDeal: true,
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed11.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed1.jpg',
      favourite: false,
      comparison: false,
      userRating: 0,
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed12.png',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      topRated: true,
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed3.png',
      favourite: false,
      comparison: false,
      userRating: 0,
      topRated: true,
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed4.jpg',
      favourite: false,
      comparison: false,
      userRating: 0,
      hotDeal: true,
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed5.jpg',
      favourite: true,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      topRated: true,
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed6.jpg',
      favourite: false,
      comparison: false,
      userRating: 0,
      topRated: true,
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed7.jpg',
      favourite: false,
      comparison: false,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed8.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      hotDeal: true,
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed9.jpg',
      favourite: false,
      comparison: false,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'bed',
      price: 30,
      stars: 0,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed10.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed11.jpg',
      favourite: true,
      comparison: false,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed8.jpg',
      favourite: false,
      comparison: false,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/bed/bed2.jpg',
      favourite: true,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-25',
      name: 'Aenean Ru Bristique 25',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/chair/chair-1.jpg',
      favourite: true,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-26',
      name: 'Aenean Ru Bristique 26',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/chair/chair-2.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-27',
      name: 'Aenean Ru Bristique 27',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/chair/chair-3.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-28',
      name: 'Aenean Ru Bristique 28',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/chair/chair-4.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-29',
      name: 'Aenean Ru Bristique 30',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/chair/chair-5.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-31',
      name: 'Aenean Ru Bristique 31',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/chair/chair-6.png',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-32',
      name: 'Aenean Ru Bristique 32',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/chair/chair-1.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-33',
      name: 'Aenean Ru Bristique 33',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: false,
      image: './images/furnitures/chair/chair-2.jpg',
      favourite: true,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-34',
      name: 'Aenean Ru Bristique 34',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/chair/chair-3.jpg',
      favourite: true,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-35',
      name: 'Aenean Ru Bristique 35',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/chair/chair-4.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      topRated: true,
    },
    {
      id: 'aenean-ru-bristique-36',
      name: 'Aenean Ru Bristique 36',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/chair/chair-5.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      topSeller: true,
      topRated: true,
    },
    {
      id: 'aenean-ru-bristique-37',
      name: 'Aenean Ru Bristique 37',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/chair/chair-6.png',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      topRated: true,
    },
    {
      id: 'aenean-ru-bristique-38',
      name: 'Aenean Ru Bristique 38',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/chair/chair-1.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-39',
      name: 'Aenean Ru Bristique 39',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/chair/chair-2.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-40',
      name: 'Aenean Ru Bristique 40',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/chair/chair-3.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-41',
      name: 'Aenean Ru Bristique 41',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/chair/chair-4.jpg',
      favourite: true,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      featured: true,
      saleOff: true,
    },
    {
      id: 'aenean-ru-bristique-42',
      name: 'Aenean Ru Bristique 42',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/sofa/sofa1.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      saleOff: true,
    },
    {
      id: 'aenean-ru-bristique-43',
      name: 'Aenean Ru Bristique 43',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/sofa/sofa2.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      saleOff: true,
    },
    {
      id: 'aenean-ru-bristique-44',
      name: 'Aenean Ru Bristique 44',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/sofa/sofa3.jpg',
      favourite: true,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-45',
      name: 'Aenean Ru Bristique 45',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/sofa/sofa4.jpg',
      favourite: true,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-46',
      name: 'Aenean Ru Bristique 46',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/sofa/sofa5.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      topSeller: true,
    },
    {
      id: 'aenean-ru-bristique-47',
      name: 'Aenean Ru Bristique 47',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/sofa/sofa1.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      topSeller: true,
      saleOff: true,
    },
    {
      id: 'aenean-ru-bristique-48',
      name: 'Aenean Ru Bristique 48',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/sofa/sofa2.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      featured: true,
      topSeller: true,
      saleOff: true,
    },
    {
      id: 'aenean-ru-bristique-49',
      name: 'Aenean Ru Bristique 49',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/sofa/sofa3.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
    },
    {
      id: 'aenean-ru-bristique-50',
      name: 'Aenean Ru Bristique 50',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/sofa/sofa4.jpg',
      favourite: true,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      featured: true,
    },
    {
      id: 'aenean-ru-bristique-51',
      name: 'Aenean Ru Bristique 51',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/sofa/sofa5.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      saleOff: true,
    },
    {
      id: 'aenean-ru-bristique-52',
      name: 'Aenean Ru Bristique 52',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/sofa/sofa1.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      featured: true,
      saleOff: true,
      topRated: true,
    },
    {
      id: 'aenean-ru-bristique-53',
      name: 'Aenean Ru Bristique 53',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/table/table1.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      featured: true,
      saleOff: true,
      topRated: true,
    },
    {
      id: 'aenean-ru-bristique-54',
      name: 'Aenean Ru Bristique 54',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      image: './images/furnitures/dining/dining1.jpg',
      favourite: false,
      comparison: false,
      oldPrice: 45,
      userRating: 0,
      featured: true,
      saleOff: true,
      topRated: true,
    },
  ],
  cart: {
    products: [],
  },

  hotDeals: {
    indoorFurniture:
      [
        './images/furnitures/hot-deals/1.jpg',
        './images/furnitures/hot-deals/2.jpg',
        './images/furnitures/hot-deals/3.png',
      ],
  },
  brands: [
    {
      id: 1,
      image: './images/brands/brand-1.png',
    },
    {
      id: 2,
      image: './images/brands/brand-2.png',
    },
    {
      id: 3,
      image: './images/brands/brand-3.png',
    },
    {
      id: 4,
      image: './images/brands/brand-4.png',
    },
    {
      id: 5,
      image: './images/brands/brand-5.png',
    },
    {
      id: 6,
      image: './images/brands/brand-6.png',
    },
    {
      id: 7,
      image: './images/brands/brand-1.png',
    },
    {
      id: 8,
      image: './images/brands/brand-2.png',
    },
  ],
  feedbacks: [
    {
      id: 1,
      comment:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mollis justo id leo cursus laoreet. Sed vulputate tempus nisi ut tincidunt. Duis dapibus dictum ligula. Integer elementum, erat ac blandit blandit, augue nunc molestie.',
      image: './images/feedback/1.jpg',
      name: 'Neo',
      client: 'Furniture client',
    },
    {
      id: 2,
      comment:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mollis justo id leo cursus laoreet. Sed vulputate tempus nisi ut tincidunt. Duis dapibus dictum ligula. Integer elementum, erat ac blandit blandit, augue nunc molestie.',
      image: './images/feedback/2.jpg',
      name: 'Gandalf',
      client: 'Furniture client',
    },
    {
      id: 3,
      comment:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean mollis justo id leo cursus laoreet. Sed vulputate tempus nisi ut tincidunt. Duis dapibus dictum ligula. Integer elementum, erat ac blandit blandit, augue nunc molestie.',
      image: './images/feedback/3.jpeg',
      name: 'Batman',
      client: 'Furniture client',
    },
  ],
};

export default initialState;
